<?php

/**
 * Implementation of hook_install().
 */
function ca_advertiser_simple_install() {
  variable_set('ca_advertiser_simple_list_template', 'ca_advertiser_simple_list_template_one');
  variable_set('ca_advertiser_simple_node_template', 'ca_advertiser_simple_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_advertiser_simple_uninstall() {
  variable_del('ca_advertiser_simple_list_template');
  variable_del('ca_advertiser_simple_node_template');
}
